À partir du nœud : 20-bullseye-slimC..p.a.R.t.I..r du nœud : 20-bullseye-slim

RUN apt-get update && apt-get install -y \UN apt-get update && apt-get install -y \
 ffmpeg \ 
 git \ 
 && rm -rf /var/lib/apt/lists/* 

Clone RUN git https://github.com/Ainz-devs/OVL-MD-V2.git /ovl_botlone RUN git https://github.com/Ainz-devs/OVL-MD-V2.git /ovl_bot

TRAVAIL /ovl_botRAVAIL /ovl_bot

RUN npm installerUN npm installer

EXPOSER 8000.XPOSER 8000.

CMD ["npm", "run", "Ovl"]MD ["npm", "run", "Ovl"]
